# Generated by Django 3.2.6 on 2021-08-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rolusuario',
            fields=[
                ('idrolusuario', models.AutoField(db_column='idRolUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rolusuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=45)),
                ('fechanac', models.DateField(blank=True, db_column='fechaNac', null=True)),
                ('fecharegistro', models.DateField(blank=True, db_column='fechaRegistro', null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idrolusuario', models.ForeignKey(db_column='idRolUsuario', on_delete=django.db.models.deletion.CASCADE, to='usuario.rolusuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
