# Generated by Django 3.2.6 on 2021-11-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipoproducto',
            fields=[
                ('idtipoproducto', models.AutoField(db_column='idTipoProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipoproducto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(null=True, upload_to='imagencomida')),
                ('visible', models.IntegerField(blank=True, null=True)),
                ('puntos', models.FloatField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idtipoproducto', models.ForeignKey(db_column='idTipoProducto', on_delete=django.db.models.deletion.CASCADE, to='producto.tipoproducto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
