# Generated by Django 3.2.6 on 2021-11-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211030_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fechanac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
