# Generated by Django 3.2.6 on 2021-11-19 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('idcupon', models.AutoField(db_column='idCupon', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(null=True, upload_to='imagencupones')),
                ('visible', models.IntegerField(blank=True, null=True)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cupon',
            },
        ),
        migrations.CreateModel(
            name='Tipocupon',
            fields=[
                ('idtipocupon', models.AutoField(db_column='idTipoCupon', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tipocupon',
            },
        ),
        migrations.CreateModel(
            name='Productocupon',
            fields=[
                ('idproductocupon', models.AutoField(db_column='idProductoCupon', primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now_add=True)),
                ('idcupon', models.ForeignKey(db_column='idCupon', on_delete=django.db.models.deletion.CASCADE, to='cupones.cupon')),
                ('idproducto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'db_table': 'productocupon',
            },
        ),
        migrations.AddField(
            model_name='cupon',
            name='idtipocupon',
            field=models.ForeignKey(db_column='idTipoCupon', on_delete=django.db.models.deletion.CASCADE, to='cupones.tipocupon'),
        ),
    ]
