# Generated by Django 3.2.6 on 2021-11-19 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('idoferta', models.AutoField(db_column='idOferta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('visible', models.IntegerField(blank=True, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('fechacreacion', models.DateTimeField(db_column='fechaCreacion')),
                ('fechamodificacion', models.DateTimeField(db_column='fechaModificacion')),
            ],
            options={
                'db_table': 'oferta',
            },
        ),
        migrations.CreateModel(
            name='Tipooferta',
            fields=[
                ('idtipooferta', models.AutoField(db_column='idTipoOferta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(db_column='fechaCreacion')),
                ('fechamodificacion', models.DateTimeField(db_column='fechaModificacion')),
            ],
            options={
                'db_table': 'tipooferta',
            },
        ),
        migrations.CreateModel(
            name='Productooferta',
            fields=[
                ('idproductooferta', models.AutoField(db_column='idProductoOferta', primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(db_column='fechaCreacion')),
                ('fechamodificacion', models.DateTimeField(db_column='fechaModificacion')),
                ('idoferta', models.ForeignKey(db_column='idOferta', on_delete=django.db.models.deletion.CASCADE, to='oferta.oferta')),
                ('idproducto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'db_table': 'productooferta',
            },
        ),
        migrations.AddField(
            model_name='oferta',
            name='idtipooferta',
            field=models.ForeignKey(db_column='idTipoOferta', on_delete=django.db.models.deletion.CASCADE, to='oferta.tipooferta'),
        ),
    ]
