# Generated by Django 3.2.6 on 2021-11-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fechamodificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenoferta'),
        ),
        migrations.AlterField(
            model_name='productooferta',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productooferta',
            name='fechamodificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tipooferta',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tipooferta',
            name='fechamodificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
